### ISSUE TITLE
Boite a encoche / Windows : Permission denied 'fablab_debug.log' en installation partagée

### ISSUE THREAD

**Issue by Rom1deTroyes** [bumblebeefr/fablab-inkscape-plugins#2]
Le Bonjour !

Avec une installation dans C:\Program Files\Inkscape\share\extensions\ j'ai une erreur quand je génère une boite à encoche.
Cette erreur ne se produit pas si l'extension est installée dans %APPDATA% je pense donc que c'est un bête problème de droits...

```
Traceback (most recent call last):
  File "fablab_box_generator.py", line 101, in <module>
    effect.affect()
  File "C:\Program Files (x86)\Inkscape\share\extensions\inkex.py", line 268, in affect
    self.effect()
  File "fablab_box_generator.py", line 80, in effect
    print_(self.options)
  File "fablab_box_generator.py", line 19, in print_
    f = open("fablab_debug.log", "a")
IOError: [Errno 13] Permission denied: 'fablab_debug.log'

```

**Comment by bumblebeefr** [comment]
Le problème devrait être corrigé (je n'ai pas de windows sous la main pour tester).

**Comment by Rom1deTroyes** [comment]
Problème résolu !

Windows 10 Famille Version 1607
Inkscape 0.91 r13725

Merci pour cette factorisation et à bientôt pour la suite !
